version: '2'
services:
  opa:
    image: openpolicyagent/opa:0.49.0-envoy
    environment:
      - AWS_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=AKIAT3ADRLAH76HWTWPE
      - AWS_SECRET_ACCESS_KEY=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
    command: ["run", "-s", "-c", "/config/config.yaml"]
    ports:
      - "8181:8181"
    volumes:
      - D:\development\opaPlayground\s3OpaBundle\s3-docker-compose\config:/config
volumes:
  config: